/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DataportKulturfinderApiModelDataLivingImageOffset } from './dataportKulturfinderApiModelDataLivingImageOffset';

export class DataportKulturfinderApiModelDataReadLivingImage {
    'title'?: string | null;
    'imageUrl'?: string | null;
    'fsetUrl'?: string | null;
    'fset3Url'?: string | null;
    'isetUrl'?: string | null;
    'videoUrl'?: string | null;
    'width'?: number;
    'height'?: number;
    'scale'?: number;
    'offset'?: DataportKulturfinderApiModelDataLivingImageOffset;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "imageUrl",
            "baseName": "imageUrl",
            "type": "string"
        },
        {
            "name": "fsetUrl",
            "baseName": "fsetUrl",
            "type": "string"
        },
        {
            "name": "fset3Url",
            "baseName": "fset3Url",
            "type": "string"
        },
        {
            "name": "isetUrl",
            "baseName": "isetUrl",
            "type": "string"
        },
        {
            "name": "videoUrl",
            "baseName": "videoUrl",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "scale",
            "baseName": "scale",
            "type": "number"
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "DataportKulturfinderApiModelDataLivingImageOffset"
        }    ];

    static getAttributeTypeMap() {
        return DataportKulturfinderApiModelDataReadLivingImage.attributeTypeMap;
    }
}

