/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DataportKulturfinderApiModelDataLivingImageOffset {
    'x'?: number;
    'y'?: number;
    'z'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "x",
            "baseName": "x",
            "type": "number"
        },
        {
            "name": "y",
            "baseName": "y",
            "type": "number"
        },
        {
            "name": "z",
            "baseName": "z",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return DataportKulturfinderApiModelDataLivingImageOffset.attributeTypeMap;
    }
}

