/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DataportKulturfinderApiModelDataWriteTranslation } from './dataportKulturfinderApiModelDataWriteTranslation';

export class DataportKulturfinderApiModelDataWriteClosedDayMultiLingual {
    'date'?: Date;
    'text'?: Array<DataportKulturfinderApiModelDataWriteTranslation> | null;
    'isEveryYear'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "Date"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "Array<DataportKulturfinderApiModelDataWriteTranslation>"
        },
        {
            "name": "isEveryYear",
            "baseName": "isEveryYear",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return DataportKulturfinderApiModelDataWriteClosedDayMultiLingual.attributeTypeMap;
    }
}

