/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DataportKulturfinderApiModelDataReadCommunication {
    'id'?: number;
    'value'?: string | null;
    'label'?: string | null;
    'communicationType'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "communicationType",
            "baseName": "communicationType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataportKulturfinderApiModelDataReadCommunication.attributeTypeMap;
    }
}

