/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DataportKulturfinderApiModelDataWriteLivingImage } from './dataportKulturfinderApiModelDataWriteLivingImage';
import { DataportKulturfinderApiModelDataWriteTranslation } from './dataportKulturfinderApiModelDataWriteTranslation';
import { DataportKulturfinderApiModelEnumsMediaType } from './dataportKulturfinderApiModelEnumsMediaType';

export class DataportKulturfinderApiModelDataWriteMediaMultiLingual {
    'id'?: number;
    'instituteId'?: number;
    'alternateText'?: Array<DataportKulturfinderApiModelDataWriteTranslation> | null;
    'copyright'?: string | null;
    'artist'?: string | null;
    'order'?: number;
    'mediaType'?: DataportKulturfinderApiModelEnumsMediaType;
    'url'?: string | null;
    'livingImage'?: DataportKulturfinderApiModelDataWriteLivingImage;
    'data'?: RequestFile | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "instituteId",
            "baseName": "instituteId",
            "type": "number"
        },
        {
            "name": "alternateText",
            "baseName": "alternateText",
            "type": "Array<DataportKulturfinderApiModelDataWriteTranslation>"
        },
        {
            "name": "copyright",
            "baseName": "copyright",
            "type": "string"
        },
        {
            "name": "artist",
            "baseName": "artist",
            "type": "string"
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "number"
        },
        {
            "name": "mediaType",
            "baseName": "mediaType",
            "type": "DataportKulturfinderApiModelEnumsMediaType"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "livingImage",
            "baseName": "livingImage",
            "type": "DataportKulturfinderApiModelDataWriteLivingImage"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "RequestFile"
        }    ];

    static getAttributeTypeMap() {
        return DataportKulturfinderApiModelDataWriteMediaMultiLingual.attributeTypeMap;
    }
}

export namespace DataportKulturfinderApiModelDataWriteMediaMultiLingual {
}
