/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DataportKulturfinderApiModelDataReadCategory } from './dataportKulturfinderApiModelDataReadCategory';
import { DataportKulturfinderApiModelDataReadClosedDay } from './dataportKulturfinderApiModelDataReadClosedDay';
import { DataportKulturfinderApiModelDataReadCommunication } from './dataportKulturfinderApiModelDataReadCommunication';
import { DataportKulturfinderApiModelDataReadMedia } from './dataportKulturfinderApiModelDataReadMedia';
import { DataportKulturfinderApiModelDataReadOpeningHours } from './dataportKulturfinderApiModelDataReadOpeningHours';
import { DataportKulturfinderApiModelDataReadRegion } from './dataportKulturfinderApiModelDataReadRegion';
import { DataportKulturfinderApiModelDataReadTag } from './dataportKulturfinderApiModelDataReadTag';

export class DataportKulturfinderApiModelDataReadInstitute {
    'id'?: number;
    'categories'?: Array<DataportKulturfinderApiModelDataReadCategory> | null;
    'tags'?: Array<DataportKulturfinderApiModelDataReadTag> | null;
    'media'?: Array<DataportKulturfinderApiModelDataReadMedia> | null;
    'dataRights'?: string | null;
    'name'?: string | null;
    'nameAddition'?: string | null;
    'description'?: string | null;
    'region'?: DataportKulturfinderApiModelDataReadRegion;
    'address'?: string | null;
    'zipCode'?: string | null;
    'city'?: string | null;
    'longitude'?: string | null;
    'latitude'?: string | null;
    'communications'?: Array<DataportKulturfinderApiModelDataReadCommunication> | null;
    'openingHours'?: Array<DataportKulturfinderApiModelDataReadOpeningHours> | null;
    'closedDays'?: Array<DataportKulturfinderApiModelDataReadClosedDay> | null;
    'specialOpeningHours'?: string | null;
    'specialClosedDays'?: string | null;
    'visible'?: boolean;
    'nameCO'?: string | null;
    'hasLivingImages'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<DataportKulturfinderApiModelDataReadCategory>"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<DataportKulturfinderApiModelDataReadTag>"
        },
        {
            "name": "media",
            "baseName": "media",
            "type": "Array<DataportKulturfinderApiModelDataReadMedia>"
        },
        {
            "name": "dataRights",
            "baseName": "dataRights",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "nameAddition",
            "baseName": "nameAddition",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "DataportKulturfinderApiModelDataReadRegion"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "zipCode",
            "baseName": "zipCode",
            "type": "string"
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string"
        },
        {
            "name": "longitude",
            "baseName": "longitude",
            "type": "string"
        },
        {
            "name": "latitude",
            "baseName": "latitude",
            "type": "string"
        },
        {
            "name": "communications",
            "baseName": "communications",
            "type": "Array<DataportKulturfinderApiModelDataReadCommunication>"
        },
        {
            "name": "openingHours",
            "baseName": "openingHours",
            "type": "Array<DataportKulturfinderApiModelDataReadOpeningHours>"
        },
        {
            "name": "closedDays",
            "baseName": "closedDays",
            "type": "Array<DataportKulturfinderApiModelDataReadClosedDay>"
        },
        {
            "name": "specialOpeningHours",
            "baseName": "specialOpeningHours",
            "type": "string"
        },
        {
            "name": "specialClosedDays",
            "baseName": "specialClosedDays",
            "type": "string"
        },
        {
            "name": "visible",
            "baseName": "visible",
            "type": "boolean"
        },
        {
            "name": "nameCO",
            "baseName": "name_c_o",
            "type": "string"
        },
        {
            "name": "hasLivingImages",
            "baseName": "hasLivingImages",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return DataportKulturfinderApiModelDataReadInstitute.attributeTypeMap;
    }
}

