/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DataportKulturfinderApiModelDataReadCommunication } from './dataportKulturfinderApiModelDataReadCommunication';
import { DataportKulturfinderApiModelDataWriteCategoryMultiLingual } from './dataportKulturfinderApiModelDataWriteCategoryMultiLingual';
import { DataportKulturfinderApiModelDataWriteClosedDayMultiLingual } from './dataportKulturfinderApiModelDataWriteClosedDayMultiLingual';
import { DataportKulturfinderApiModelDataWriteMediaMultiLingual } from './dataportKulturfinderApiModelDataWriteMediaMultiLingual';
import { DataportKulturfinderApiModelDataWriteOpeningHoursMultiLingual } from './dataportKulturfinderApiModelDataWriteOpeningHoursMultiLingual';
import { DataportKulturfinderApiModelDataWriteRegionMultiLingual } from './dataportKulturfinderApiModelDataWriteRegionMultiLingual';
import { DataportKulturfinderApiModelDataWriteTagMultiLingual } from './dataportKulturfinderApiModelDataWriteTagMultiLingual';
import { DataportKulturfinderApiModelDataWriteTranslation } from './dataportKulturfinderApiModelDataWriteTranslation';

export class DataportKulturfinderApiModelDataWriteInstituteMultiLingual {
    'id'?: number;
    'categories'?: Array<DataportKulturfinderApiModelDataWriteCategoryMultiLingual> | null;
    'tags'?: Array<DataportKulturfinderApiModelDataWriteTagMultiLingual> | null;
    'media'?: Array<DataportKulturfinderApiModelDataWriteMediaMultiLingual> | null;
    'communications'?: Array<DataportKulturfinderApiModelDataReadCommunication> | null;
    'openingHours'?: Array<DataportKulturfinderApiModelDataWriteOpeningHoursMultiLingual> | null;
    'closedDays'?: Array<DataportKulturfinderApiModelDataWriteClosedDayMultiLingual> | null;
    'specialOpeningHours'?: Array<DataportKulturfinderApiModelDataWriteTranslation> | null;
    'specialClosedDays'?: Array<DataportKulturfinderApiModelDataWriteTranslation> | null;
    'visible'?: boolean;
    'dataRights'?: string | null;
    'name'?: Array<DataportKulturfinderApiModelDataWriteTranslation> | null;
    'nameAddition'?: Array<DataportKulturfinderApiModelDataWriteTranslation> | null;
    'description'?: Array<DataportKulturfinderApiModelDataWriteTranslation> | null;
    'region'?: DataportKulturfinderApiModelDataWriteRegionMultiLingual;
    'address'?: Array<DataportKulturfinderApiModelDataWriteTranslation> | null;
    'nameCO'?: string | null;
    'zipCode'?: string | null;
    'city'?: Array<DataportKulturfinderApiModelDataWriteTranslation> | null;
    'longitude'?: string | null;
    'latitude'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<DataportKulturfinderApiModelDataWriteCategoryMultiLingual>"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<DataportKulturfinderApiModelDataWriteTagMultiLingual>"
        },
        {
            "name": "media",
            "baseName": "media",
            "type": "Array<DataportKulturfinderApiModelDataWriteMediaMultiLingual>"
        },
        {
            "name": "communications",
            "baseName": "communications",
            "type": "Array<DataportKulturfinderApiModelDataReadCommunication>"
        },
        {
            "name": "openingHours",
            "baseName": "openingHours",
            "type": "Array<DataportKulturfinderApiModelDataWriteOpeningHoursMultiLingual>"
        },
        {
            "name": "closedDays",
            "baseName": "closedDays",
            "type": "Array<DataportKulturfinderApiModelDataWriteClosedDayMultiLingual>"
        },
        {
            "name": "specialOpeningHours",
            "baseName": "specialOpeningHours",
            "type": "Array<DataportKulturfinderApiModelDataWriteTranslation>"
        },
        {
            "name": "specialClosedDays",
            "baseName": "specialClosedDays",
            "type": "Array<DataportKulturfinderApiModelDataWriteTranslation>"
        },
        {
            "name": "visible",
            "baseName": "visible",
            "type": "boolean"
        },
        {
            "name": "dataRights",
            "baseName": "dataRights",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "Array<DataportKulturfinderApiModelDataWriteTranslation>"
        },
        {
            "name": "nameAddition",
            "baseName": "nameAddition",
            "type": "Array<DataportKulturfinderApiModelDataWriteTranslation>"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "Array<DataportKulturfinderApiModelDataWriteTranslation>"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "DataportKulturfinderApiModelDataWriteRegionMultiLingual"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "Array<DataportKulturfinderApiModelDataWriteTranslation>"
        },
        {
            "name": "nameCO",
            "baseName": "name_c_o",
            "type": "string"
        },
        {
            "name": "zipCode",
            "baseName": "zipCode",
            "type": "string"
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "Array<DataportKulturfinderApiModelDataWriteTranslation>"
        },
        {
            "name": "longitude",
            "baseName": "longitude",
            "type": "string"
        },
        {
            "name": "latitude",
            "baseName": "latitude",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataportKulturfinderApiModelDataWriteInstituteMultiLingual.attributeTypeMap;
    }
}

