/* tslint:disable */
/* eslint-disable */
/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataportKulturfinderApiModelDataReadMedia } from './DataportKulturfinderApiModelDataReadMedia';
import {
    DataportKulturfinderApiModelDataReadMediaFromJSON,
    DataportKulturfinderApiModelDataReadMediaFromJSONTyped,
    DataportKulturfinderApiModelDataReadMediaToJSON,
    DataportKulturfinderApiModelDataReadMediaToJSONTyped,
} from './DataportKulturfinderApiModelDataReadMedia';
import type { DataportKulturfinderApiModelDataReadRegion } from './DataportKulturfinderApiModelDataReadRegion';
import {
    DataportKulturfinderApiModelDataReadRegionFromJSON,
    DataportKulturfinderApiModelDataReadRegionFromJSONTyped,
    DataportKulturfinderApiModelDataReadRegionToJSON,
    DataportKulturfinderApiModelDataReadRegionToJSONTyped,
} from './DataportKulturfinderApiModelDataReadRegion';
import type { DataportKulturfinderApiModelDataReadCategory } from './DataportKulturfinderApiModelDataReadCategory';
import {
    DataportKulturfinderApiModelDataReadCategoryFromJSON,
    DataportKulturfinderApiModelDataReadCategoryFromJSONTyped,
    DataportKulturfinderApiModelDataReadCategoryToJSON,
    DataportKulturfinderApiModelDataReadCategoryToJSONTyped,
} from './DataportKulturfinderApiModelDataReadCategory';
import type { DataportKulturfinderApiModelDataReadTag } from './DataportKulturfinderApiModelDataReadTag';
import {
    DataportKulturfinderApiModelDataReadTagFromJSON,
    DataportKulturfinderApiModelDataReadTagFromJSONTyped,
    DataportKulturfinderApiModelDataReadTagToJSON,
    DataportKulturfinderApiModelDataReadTagToJSONTyped,
} from './DataportKulturfinderApiModelDataReadTag';

/**
 * 
 * @export
 * @interface DataportKulturfinderApiModelDataReadBasicInstitute
 */
export interface DataportKulturfinderApiModelDataReadBasicInstitute {
    /**
     * 
     * @type {number}
     * @memberof DataportKulturfinderApiModelDataReadBasicInstitute
     */
    id?: number;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataReadCategory>}
     * @memberof DataportKulturfinderApiModelDataReadBasicInstitute
     */
    categories?: Array<DataportKulturfinderApiModelDataReadCategory> | null;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataReadTag>}
     * @memberof DataportKulturfinderApiModelDataReadBasicInstitute
     */
    tags?: Array<DataportKulturfinderApiModelDataReadTag> | null;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataReadMedia>}
     * @memberof DataportKulturfinderApiModelDataReadBasicInstitute
     */
    media?: Array<DataportKulturfinderApiModelDataReadMedia> | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadBasicInstitute
     */
    dataRights?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadBasicInstitute
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadBasicInstitute
     */
    nameAddition?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadBasicInstitute
     */
    description?: string | null;
    /**
     * 
     * @type {DataportKulturfinderApiModelDataReadRegion}
     * @memberof DataportKulturfinderApiModelDataReadBasicInstitute
     */
    region?: DataportKulturfinderApiModelDataReadRegion;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadBasicInstitute
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadBasicInstitute
     */
    zipCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadBasicInstitute
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadBasicInstitute
     */
    longitude?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadBasicInstitute
     */
    latitude?: string | null;
}

/**
 * Check if a given object implements the DataportKulturfinderApiModelDataReadBasicInstitute interface.
 */
export function instanceOfDataportKulturfinderApiModelDataReadBasicInstitute(value: object): value is DataportKulturfinderApiModelDataReadBasicInstitute {
    return true;
}

export function DataportKulturfinderApiModelDataReadBasicInstituteFromJSON(json: any): DataportKulturfinderApiModelDataReadBasicInstitute {
    return DataportKulturfinderApiModelDataReadBasicInstituteFromJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataReadBasicInstituteFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataportKulturfinderApiModelDataReadBasicInstitute {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'categories': json['categories'] == null ? undefined : ((json['categories'] as Array<any>).map(DataportKulturfinderApiModelDataReadCategoryFromJSON)),
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(DataportKulturfinderApiModelDataReadTagFromJSON)),
        'media': json['media'] == null ? undefined : ((json['media'] as Array<any>).map(DataportKulturfinderApiModelDataReadMediaFromJSON)),
        'dataRights': json['dataRights'] == null ? undefined : json['dataRights'],
        'name': json['name'] == null ? undefined : json['name'],
        'nameAddition': json['nameAddition'] == null ? undefined : json['nameAddition'],
        'description': json['description'] == null ? undefined : json['description'],
        'region': json['region'] == null ? undefined : DataportKulturfinderApiModelDataReadRegionFromJSON(json['region']),
        'address': json['address'] == null ? undefined : json['address'],
        'zipCode': json['zipCode'] == null ? undefined : json['zipCode'],
        'city': json['city'] == null ? undefined : json['city'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
    };
}

export function DataportKulturfinderApiModelDataReadBasicInstituteToJSON(json: any): DataportKulturfinderApiModelDataReadBasicInstitute {
    return DataportKulturfinderApiModelDataReadBasicInstituteToJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataReadBasicInstituteToJSONTyped(value?: DataportKulturfinderApiModelDataReadBasicInstitute | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'categories': value['categories'] == null ? undefined : ((value['categories'] as Array<any>).map(DataportKulturfinderApiModelDataReadCategoryToJSON)),
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(DataportKulturfinderApiModelDataReadTagToJSON)),
        'media': value['media'] == null ? undefined : ((value['media'] as Array<any>).map(DataportKulturfinderApiModelDataReadMediaToJSON)),
        'dataRights': value['dataRights'],
        'name': value['name'],
        'nameAddition': value['nameAddition'],
        'description': value['description'],
        'region': DataportKulturfinderApiModelDataReadRegionToJSON(value['region']),
        'address': value['address'],
        'zipCode': value['zipCode'],
        'city': value['city'],
        'longitude': value['longitude'],
        'latitude': value['latitude'],
    };
}

