/* tslint:disable */
/* eslint-disable */
/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataportKulturfinderApiModelDataWriteTranslation
 */
export interface DataportKulturfinderApiModelDataWriteTranslation {
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataWriteTranslation
     */
    language?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataWriteTranslation
     */
    text?: string | null;
}

/**
 * Check if a given object implements the DataportKulturfinderApiModelDataWriteTranslation interface.
 */
export function instanceOfDataportKulturfinderApiModelDataWriteTranslation(value: object): value is DataportKulturfinderApiModelDataWriteTranslation {
    return true;
}

export function DataportKulturfinderApiModelDataWriteTranslationFromJSON(json: any): DataportKulturfinderApiModelDataWriteTranslation {
    return DataportKulturfinderApiModelDataWriteTranslationFromJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataWriteTranslationFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataportKulturfinderApiModelDataWriteTranslation {
    if (json == null) {
        return json;
    }
    return {
        
        'language': json['language'] == null ? undefined : json['language'],
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function DataportKulturfinderApiModelDataWriteTranslationToJSON(json: any): DataportKulturfinderApiModelDataWriteTranslation {
    return DataportKulturfinderApiModelDataWriteTranslationToJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataWriteTranslationToJSONTyped(value?: DataportKulturfinderApiModelDataWriteTranslation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'language': value['language'],
        'text': value['text'],
    };
}

