/* tslint:disable */
/* eslint-disable */
/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataportKulturfinderApiModelDataReadClosedDay
 */
export interface DataportKulturfinderApiModelDataReadClosedDay {
    /**
     * 
     * @type {Date}
     * @memberof DataportKulturfinderApiModelDataReadClosedDay
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadClosedDay
     */
    text?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DataportKulturfinderApiModelDataReadClosedDay
     */
    isEveryYear?: boolean;
}

/**
 * Check if a given object implements the DataportKulturfinderApiModelDataReadClosedDay interface.
 */
export function instanceOfDataportKulturfinderApiModelDataReadClosedDay(value: object): value is DataportKulturfinderApiModelDataReadClosedDay {
    return true;
}

export function DataportKulturfinderApiModelDataReadClosedDayFromJSON(json: any): DataportKulturfinderApiModelDataReadClosedDay {
    return DataportKulturfinderApiModelDataReadClosedDayFromJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataReadClosedDayFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataportKulturfinderApiModelDataReadClosedDay {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'text': json['text'] == null ? undefined : json['text'],
        'isEveryYear': json['isEveryYear'] == null ? undefined : json['isEveryYear'],
    };
}

export function DataportKulturfinderApiModelDataReadClosedDayToJSON(json: any): DataportKulturfinderApiModelDataReadClosedDay {
    return DataportKulturfinderApiModelDataReadClosedDayToJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataReadClosedDayToJSONTyped(value?: DataportKulturfinderApiModelDataReadClosedDay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'] == null ? undefined : ((value['date']).toISOString().substring(0,10)),
        'text': value['text'],
        'isEveryYear': value['isEveryYear'],
    };
}

