/* tslint:disable */
/* eslint-disable */
/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataportKulturfinderApiModelDataLivingImageOffset
 */
export interface DataportKulturfinderApiModelDataLivingImageOffset {
    /**
     * 
     * @type {number}
     * @memberof DataportKulturfinderApiModelDataLivingImageOffset
     */
    x?: number;
    /**
     * 
     * @type {number}
     * @memberof DataportKulturfinderApiModelDataLivingImageOffset
     */
    y?: number;
    /**
     * 
     * @type {number}
     * @memberof DataportKulturfinderApiModelDataLivingImageOffset
     */
    z?: number;
}

/**
 * Check if a given object implements the DataportKulturfinderApiModelDataLivingImageOffset interface.
 */
export function instanceOfDataportKulturfinderApiModelDataLivingImageOffset(value: object): value is DataportKulturfinderApiModelDataLivingImageOffset {
    return true;
}

export function DataportKulturfinderApiModelDataLivingImageOffsetFromJSON(json: any): DataportKulturfinderApiModelDataLivingImageOffset {
    return DataportKulturfinderApiModelDataLivingImageOffsetFromJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataLivingImageOffsetFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataportKulturfinderApiModelDataLivingImageOffset {
    if (json == null) {
        return json;
    }
    return {
        
        'x': json['x'] == null ? undefined : json['x'],
        'y': json['y'] == null ? undefined : json['y'],
        'z': json['z'] == null ? undefined : json['z'],
    };
}

export function DataportKulturfinderApiModelDataLivingImageOffsetToJSON(json: any): DataportKulturfinderApiModelDataLivingImageOffset {
    return DataportKulturfinderApiModelDataLivingImageOffsetToJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataLivingImageOffsetToJSONTyped(value?: DataportKulturfinderApiModelDataLivingImageOffset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'x': value['x'],
        'y': value['y'],
        'z': value['z'],
    };
}

