/* tslint:disable */
/* eslint-disable */
/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataportKulturfinderApiModelDataWriteTranslation } from './DataportKulturfinderApiModelDataWriteTranslation';
import {
    DataportKulturfinderApiModelDataWriteTranslationFromJSON,
    DataportKulturfinderApiModelDataWriteTranslationFromJSONTyped,
    DataportKulturfinderApiModelDataWriteTranslationToJSON,
    DataportKulturfinderApiModelDataWriteTranslationToJSONTyped,
} from './DataportKulturfinderApiModelDataWriteTranslation';

/**
 * 
 * @export
 * @interface DataportKulturfinderApiModelDataWriteTagMultiLingual
 */
export interface DataportKulturfinderApiModelDataWriteTagMultiLingual {
    /**
     * 
     * @type {number}
     * @memberof DataportKulturfinderApiModelDataWriteTagMultiLingual
     */
    id?: number;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataWriteTranslation>}
     * @memberof DataportKulturfinderApiModelDataWriteTagMultiLingual
     */
    text?: Array<DataportKulturfinderApiModelDataWriteTranslation> | null;
}

/**
 * Check if a given object implements the DataportKulturfinderApiModelDataWriteTagMultiLingual interface.
 */
export function instanceOfDataportKulturfinderApiModelDataWriteTagMultiLingual(value: object): value is DataportKulturfinderApiModelDataWriteTagMultiLingual {
    return true;
}

export function DataportKulturfinderApiModelDataWriteTagMultiLingualFromJSON(json: any): DataportKulturfinderApiModelDataWriteTagMultiLingual {
    return DataportKulturfinderApiModelDataWriteTagMultiLingualFromJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataWriteTagMultiLingualFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataportKulturfinderApiModelDataWriteTagMultiLingual {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'text': json['text'] == null ? undefined : ((json['text'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTranslationFromJSON)),
    };
}

export function DataportKulturfinderApiModelDataWriteTagMultiLingualToJSON(json: any): DataportKulturfinderApiModelDataWriteTagMultiLingual {
    return DataportKulturfinderApiModelDataWriteTagMultiLingualToJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataWriteTagMultiLingualToJSONTyped(value?: DataportKulturfinderApiModelDataWriteTagMultiLingual | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'text': value['text'] == null ? undefined : ((value['text'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTranslationToJSON)),
    };
}

