/* tslint:disable */
/* eslint-disable */
/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataportKulturfinderApiModelDataReadTag
 */
export interface DataportKulturfinderApiModelDataReadTag {
    /**
     * 
     * @type {number}
     * @memberof DataportKulturfinderApiModelDataReadTag
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadTag
     */
    name?: string | null;
}

/**
 * Check if a given object implements the DataportKulturfinderApiModelDataReadTag interface.
 */
export function instanceOfDataportKulturfinderApiModelDataReadTag(value: object): value is DataportKulturfinderApiModelDataReadTag {
    return true;
}

export function DataportKulturfinderApiModelDataReadTagFromJSON(json: any): DataportKulturfinderApiModelDataReadTag {
    return DataportKulturfinderApiModelDataReadTagFromJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataReadTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataportKulturfinderApiModelDataReadTag {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function DataportKulturfinderApiModelDataReadTagToJSON(json: any): DataportKulturfinderApiModelDataReadTag {
    return DataportKulturfinderApiModelDataReadTagToJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataReadTagToJSONTyped(value?: DataportKulturfinderApiModelDataReadTag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

