/* tslint:disable */
/* eslint-disable */
/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataportKulturfinderApiModelDataReadRegion
 */
export interface DataportKulturfinderApiModelDataReadRegion {
    /**
     * 
     * @type {number}
     * @memberof DataportKulturfinderApiModelDataReadRegion
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadRegion
     */
    state?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadRegion
     */
    name?: string | null;
}

/**
 * Check if a given object implements the DataportKulturfinderApiModelDataReadRegion interface.
 */
export function instanceOfDataportKulturfinderApiModelDataReadRegion(value: object): value is DataportKulturfinderApiModelDataReadRegion {
    return true;
}

export function DataportKulturfinderApiModelDataReadRegionFromJSON(json: any): DataportKulturfinderApiModelDataReadRegion {
    return DataportKulturfinderApiModelDataReadRegionFromJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataReadRegionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataportKulturfinderApiModelDataReadRegion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'state': json['state'] == null ? undefined : json['state'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function DataportKulturfinderApiModelDataReadRegionToJSON(json: any): DataportKulturfinderApiModelDataReadRegion {
    return DataportKulturfinderApiModelDataReadRegionToJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataReadRegionToJSONTyped(value?: DataportKulturfinderApiModelDataReadRegion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'state': value['state'],
        'name': value['name'],
    };
}

