/* tslint:disable */
/* eslint-disable */
/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataportKulturfinderApiModelDataLivingImageOffset } from './DataportKulturfinderApiModelDataLivingImageOffset';
import {
    DataportKulturfinderApiModelDataLivingImageOffsetFromJSON,
    DataportKulturfinderApiModelDataLivingImageOffsetFromJSONTyped,
    DataportKulturfinderApiModelDataLivingImageOffsetToJSON,
    DataportKulturfinderApiModelDataLivingImageOffsetToJSONTyped,
} from './DataportKulturfinderApiModelDataLivingImageOffset';

/**
 * 
 * @export
 * @interface DataportKulturfinderApiModelDataWriteLivingImage
 */
export interface DataportKulturfinderApiModelDataWriteLivingImage {
    /**
     * 
     * @type {number}
     * @memberof DataportKulturfinderApiModelDataWriteLivingImage
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataWriteLivingImage
     */
    title?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DataportKulturfinderApiModelDataWriteLivingImage
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof DataportKulturfinderApiModelDataWriteLivingImage
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof DataportKulturfinderApiModelDataWriteLivingImage
     */
    scale?: number;
    /**
     * 
     * @type {DataportKulturfinderApiModelDataLivingImageOffset}
     * @memberof DataportKulturfinderApiModelDataWriteLivingImage
     */
    offset?: DataportKulturfinderApiModelDataLivingImageOffset;
    /**
     * 
     * @type {Blob}
     * @memberof DataportKulturfinderApiModelDataWriteLivingImage
     */
    fset?: Blob | null;
    /**
     * 
     * @type {Blob}
     * @memberof DataportKulturfinderApiModelDataWriteLivingImage
     */
    fset3?: Blob | null;
    /**
     * 
     * @type {Blob}
     * @memberof DataportKulturfinderApiModelDataWriteLivingImage
     */
    iset?: Blob | null;
}

/**
 * Check if a given object implements the DataportKulturfinderApiModelDataWriteLivingImage interface.
 */
export function instanceOfDataportKulturfinderApiModelDataWriteLivingImage(value: object): value is DataportKulturfinderApiModelDataWriteLivingImage {
    return true;
}

export function DataportKulturfinderApiModelDataWriteLivingImageFromJSON(json: any): DataportKulturfinderApiModelDataWriteLivingImage {
    return DataportKulturfinderApiModelDataWriteLivingImageFromJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataWriteLivingImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataportKulturfinderApiModelDataWriteLivingImage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
        'scale': json['scale'] == null ? undefined : json['scale'],
        'offset': json['offset'] == null ? undefined : DataportKulturfinderApiModelDataLivingImageOffsetFromJSON(json['offset']),
        'fset': json['fset'] == null ? undefined : json['fset'],
        'fset3': json['fset3'] == null ? undefined : json['fset3'],
        'iset': json['iset'] == null ? undefined : json['iset'],
    };
}

export function DataportKulturfinderApiModelDataWriteLivingImageToJSON(json: any): DataportKulturfinderApiModelDataWriteLivingImage {
    return DataportKulturfinderApiModelDataWriteLivingImageToJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataWriteLivingImageToJSONTyped(value?: DataportKulturfinderApiModelDataWriteLivingImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'width': value['width'],
        'height': value['height'],
        'scale': value['scale'],
        'offset': DataportKulturfinderApiModelDataLivingImageOffsetToJSON(value['offset']),
        'fset': value['fset'],
        'fset3': value['fset3'],
        'iset': value['iset'],
    };
}

