/* tslint:disable */
/* eslint-disable */
/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataportKulturfinderApiModelDataWriteTranslation } from './DataportKulturfinderApiModelDataWriteTranslation';
import {
    DataportKulturfinderApiModelDataWriteTranslationFromJSON,
    DataportKulturfinderApiModelDataWriteTranslationFromJSONTyped,
    DataportKulturfinderApiModelDataWriteTranslationToJSON,
    DataportKulturfinderApiModelDataWriteTranslationToJSONTyped,
} from './DataportKulturfinderApiModelDataWriteTranslation';

/**
 * 
 * @export
 * @interface DataportKulturfinderApiModelDataWriteClosedDayMultiLingual
 */
export interface DataportKulturfinderApiModelDataWriteClosedDayMultiLingual {
    /**
     * 
     * @type {Date}
     * @memberof DataportKulturfinderApiModelDataWriteClosedDayMultiLingual
     */
    date?: Date;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataWriteTranslation>}
     * @memberof DataportKulturfinderApiModelDataWriteClosedDayMultiLingual
     */
    text?: Array<DataportKulturfinderApiModelDataWriteTranslation> | null;
    /**
     * 
     * @type {boolean}
     * @memberof DataportKulturfinderApiModelDataWriteClosedDayMultiLingual
     */
    isEveryYear?: boolean;
}

/**
 * Check if a given object implements the DataportKulturfinderApiModelDataWriteClosedDayMultiLingual interface.
 */
export function instanceOfDataportKulturfinderApiModelDataWriteClosedDayMultiLingual(value: object): value is DataportKulturfinderApiModelDataWriteClosedDayMultiLingual {
    return true;
}

export function DataportKulturfinderApiModelDataWriteClosedDayMultiLingualFromJSON(json: any): DataportKulturfinderApiModelDataWriteClosedDayMultiLingual {
    return DataportKulturfinderApiModelDataWriteClosedDayMultiLingualFromJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataWriteClosedDayMultiLingualFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataportKulturfinderApiModelDataWriteClosedDayMultiLingual {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'text': json['text'] == null ? undefined : ((json['text'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTranslationFromJSON)),
        'isEveryYear': json['isEveryYear'] == null ? undefined : json['isEveryYear'],
    };
}

export function DataportKulturfinderApiModelDataWriteClosedDayMultiLingualToJSON(json: any): DataportKulturfinderApiModelDataWriteClosedDayMultiLingual {
    return DataportKulturfinderApiModelDataWriteClosedDayMultiLingualToJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataWriteClosedDayMultiLingualToJSONTyped(value?: DataportKulturfinderApiModelDataWriteClosedDayMultiLingual | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'] == null ? undefined : ((value['date']).toISOString()),
        'text': value['text'] == null ? undefined : ((value['text'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTranslationToJSON)),
        'isEveryYear': value['isEveryYear'],
    };
}

