/* tslint:disable */
/* eslint-disable */
/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataportKulturfinderApiModelDataUser
 */
export interface DataportKulturfinderApiModelDataUser {
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataUser
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataUser
     */
    password?: string | null;
}

/**
 * Check if a given object implements the DataportKulturfinderApiModelDataUser interface.
 */
export function instanceOfDataportKulturfinderApiModelDataUser(value: object): value is DataportKulturfinderApiModelDataUser {
    return true;
}

export function DataportKulturfinderApiModelDataUserFromJSON(json: any): DataportKulturfinderApiModelDataUser {
    return DataportKulturfinderApiModelDataUserFromJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataportKulturfinderApiModelDataUser {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function DataportKulturfinderApiModelDataUserToJSON(json: any): DataportKulturfinderApiModelDataUser {
    return DataportKulturfinderApiModelDataUserToJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataUserToJSONTyped(value?: DataportKulturfinderApiModelDataUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'password': value['password'],
    };
}

