/* tslint:disable */
/* eslint-disable */
/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataportKulturfinderApiModelDataWriteTranslation } from './DataportKulturfinderApiModelDataWriteTranslation';
import {
    DataportKulturfinderApiModelDataWriteTranslationFromJSON,
    DataportKulturfinderApiModelDataWriteTranslationFromJSONTyped,
    DataportKulturfinderApiModelDataWriteTranslationToJSON,
    DataportKulturfinderApiModelDataWriteTranslationToJSONTyped,
} from './DataportKulturfinderApiModelDataWriteTranslation';

/**
 * 
 * @export
 * @interface DataportKulturfinderApiModelDataWriteCategoryMultiLingual
 */
export interface DataportKulturfinderApiModelDataWriteCategoryMultiLingual {
    /**
     * 
     * @type {number}
     * @memberof DataportKulturfinderApiModelDataWriteCategoryMultiLingual
     */
    id?: number;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataWriteTranslation>}
     * @memberof DataportKulturfinderApiModelDataWriteCategoryMultiLingual
     */
    name?: Array<DataportKulturfinderApiModelDataWriteTranslation> | null;
}

/**
 * Check if a given object implements the DataportKulturfinderApiModelDataWriteCategoryMultiLingual interface.
 */
export function instanceOfDataportKulturfinderApiModelDataWriteCategoryMultiLingual(value: object): value is DataportKulturfinderApiModelDataWriteCategoryMultiLingual {
    return true;
}

export function DataportKulturfinderApiModelDataWriteCategoryMultiLingualFromJSON(json: any): DataportKulturfinderApiModelDataWriteCategoryMultiLingual {
    return DataportKulturfinderApiModelDataWriteCategoryMultiLingualFromJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataWriteCategoryMultiLingualFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataportKulturfinderApiModelDataWriteCategoryMultiLingual {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : ((json['name'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTranslationFromJSON)),
    };
}

export function DataportKulturfinderApiModelDataWriteCategoryMultiLingualToJSON(json: any): DataportKulturfinderApiModelDataWriteCategoryMultiLingual {
    return DataportKulturfinderApiModelDataWriteCategoryMultiLingualToJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataWriteCategoryMultiLingualToJSONTyped(value?: DataportKulturfinderApiModelDataWriteCategoryMultiLingual | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'] == null ? undefined : ((value['name'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTranslationToJSON)),
    };
}

