/* tslint:disable */
/* eslint-disable */
/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataportKulturfinderApiModelDataReadMedia } from './DataportKulturfinderApiModelDataReadMedia';
import {
    DataportKulturfinderApiModelDataReadMediaFromJSON,
    DataportKulturfinderApiModelDataReadMediaFromJSONTyped,
    DataportKulturfinderApiModelDataReadMediaToJSON,
    DataportKulturfinderApiModelDataReadMediaToJSONTyped,
} from './DataportKulturfinderApiModelDataReadMedia';
import type { DataportKulturfinderApiModelDataReadRegion } from './DataportKulturfinderApiModelDataReadRegion';
import {
    DataportKulturfinderApiModelDataReadRegionFromJSON,
    DataportKulturfinderApiModelDataReadRegionFromJSONTyped,
    DataportKulturfinderApiModelDataReadRegionToJSON,
    DataportKulturfinderApiModelDataReadRegionToJSONTyped,
} from './DataportKulturfinderApiModelDataReadRegion';
import type { DataportKulturfinderApiModelDataReadOpeningHours } from './DataportKulturfinderApiModelDataReadOpeningHours';
import {
    DataportKulturfinderApiModelDataReadOpeningHoursFromJSON,
    DataportKulturfinderApiModelDataReadOpeningHoursFromJSONTyped,
    DataportKulturfinderApiModelDataReadOpeningHoursToJSON,
    DataportKulturfinderApiModelDataReadOpeningHoursToJSONTyped,
} from './DataportKulturfinderApiModelDataReadOpeningHours';
import type { DataportKulturfinderApiModelDataReadCategory } from './DataportKulturfinderApiModelDataReadCategory';
import {
    DataportKulturfinderApiModelDataReadCategoryFromJSON,
    DataportKulturfinderApiModelDataReadCategoryFromJSONTyped,
    DataportKulturfinderApiModelDataReadCategoryToJSON,
    DataportKulturfinderApiModelDataReadCategoryToJSONTyped,
} from './DataportKulturfinderApiModelDataReadCategory';
import type { DataportKulturfinderApiModelDataReadClosedDay } from './DataportKulturfinderApiModelDataReadClosedDay';
import {
    DataportKulturfinderApiModelDataReadClosedDayFromJSON,
    DataportKulturfinderApiModelDataReadClosedDayFromJSONTyped,
    DataportKulturfinderApiModelDataReadClosedDayToJSON,
    DataportKulturfinderApiModelDataReadClosedDayToJSONTyped,
} from './DataportKulturfinderApiModelDataReadClosedDay';
import type { DataportKulturfinderApiModelDataReadTag } from './DataportKulturfinderApiModelDataReadTag';
import {
    DataportKulturfinderApiModelDataReadTagFromJSON,
    DataportKulturfinderApiModelDataReadTagFromJSONTyped,
    DataportKulturfinderApiModelDataReadTagToJSON,
    DataportKulturfinderApiModelDataReadTagToJSONTyped,
} from './DataportKulturfinderApiModelDataReadTag';
import type { DataportKulturfinderApiModelDataReadCommunication } from './DataportKulturfinderApiModelDataReadCommunication';
import {
    DataportKulturfinderApiModelDataReadCommunicationFromJSON,
    DataportKulturfinderApiModelDataReadCommunicationFromJSONTyped,
    DataportKulturfinderApiModelDataReadCommunicationToJSON,
    DataportKulturfinderApiModelDataReadCommunicationToJSONTyped,
} from './DataportKulturfinderApiModelDataReadCommunication';

/**
 * 
 * @export
 * @interface DataportKulturfinderApiModelDataReadInstitute
 */
export interface DataportKulturfinderApiModelDataReadInstitute {
    /**
     * 
     * @type {number}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    id?: number;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataReadCategory>}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    categories?: Array<DataportKulturfinderApiModelDataReadCategory> | null;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataReadTag>}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    tags?: Array<DataportKulturfinderApiModelDataReadTag> | null;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataReadMedia>}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    media?: Array<DataportKulturfinderApiModelDataReadMedia> | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    dataRights?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    nameAddition?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    description?: string | null;
    /**
     * 
     * @type {DataportKulturfinderApiModelDataReadRegion}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    region?: DataportKulturfinderApiModelDataReadRegion;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    zipCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    longitude?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    latitude?: string | null;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataReadCommunication>}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    communications?: Array<DataportKulturfinderApiModelDataReadCommunication> | null;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataReadOpeningHours>}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    openingHours?: Array<DataportKulturfinderApiModelDataReadOpeningHours> | null;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataReadClosedDay>}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    closedDays?: Array<DataportKulturfinderApiModelDataReadClosedDay> | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    specialOpeningHours?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    specialClosedDays?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    visible?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    nameCO?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DataportKulturfinderApiModelDataReadInstitute
     */
    hasLivingImages?: boolean;
}

/**
 * Check if a given object implements the DataportKulturfinderApiModelDataReadInstitute interface.
 */
export function instanceOfDataportKulturfinderApiModelDataReadInstitute(value: object): value is DataportKulturfinderApiModelDataReadInstitute {
    return true;
}

export function DataportKulturfinderApiModelDataReadInstituteFromJSON(json: any): DataportKulturfinderApiModelDataReadInstitute {
    return DataportKulturfinderApiModelDataReadInstituteFromJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataReadInstituteFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataportKulturfinderApiModelDataReadInstitute {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'categories': json['categories'] == null ? undefined : ((json['categories'] as Array<any>).map(DataportKulturfinderApiModelDataReadCategoryFromJSON)),
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(DataportKulturfinderApiModelDataReadTagFromJSON)),
        'media': json['media'] == null ? undefined : ((json['media'] as Array<any>).map(DataportKulturfinderApiModelDataReadMediaFromJSON)),
        'dataRights': json['dataRights'] == null ? undefined : json['dataRights'],
        'name': json['name'] == null ? undefined : json['name'],
        'nameAddition': json['nameAddition'] == null ? undefined : json['nameAddition'],
        'description': json['description'] == null ? undefined : json['description'],
        'region': json['region'] == null ? undefined : DataportKulturfinderApiModelDataReadRegionFromJSON(json['region']),
        'address': json['address'] == null ? undefined : json['address'],
        'zipCode': json['zipCode'] == null ? undefined : json['zipCode'],
        'city': json['city'] == null ? undefined : json['city'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'communications': json['communications'] == null ? undefined : ((json['communications'] as Array<any>).map(DataportKulturfinderApiModelDataReadCommunicationFromJSON)),
        'openingHours': json['openingHours'] == null ? undefined : ((json['openingHours'] as Array<any>).map(DataportKulturfinderApiModelDataReadOpeningHoursFromJSON)),
        'closedDays': json['closedDays'] == null ? undefined : ((json['closedDays'] as Array<any>).map(DataportKulturfinderApiModelDataReadClosedDayFromJSON)),
        'specialOpeningHours': json['specialOpeningHours'] == null ? undefined : json['specialOpeningHours'],
        'specialClosedDays': json['specialClosedDays'] == null ? undefined : json['specialClosedDays'],
        'visible': json['visible'] == null ? undefined : json['visible'],
        'nameCO': json['name_c_o'] == null ? undefined : json['name_c_o'],
        'hasLivingImages': json['hasLivingImages'] == null ? undefined : json['hasLivingImages'],
    };
}

export function DataportKulturfinderApiModelDataReadInstituteToJSON(json: any): DataportKulturfinderApiModelDataReadInstitute {
    return DataportKulturfinderApiModelDataReadInstituteToJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataReadInstituteToJSONTyped(value?: DataportKulturfinderApiModelDataReadInstitute | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'categories': value['categories'] == null ? undefined : ((value['categories'] as Array<any>).map(DataportKulturfinderApiModelDataReadCategoryToJSON)),
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(DataportKulturfinderApiModelDataReadTagToJSON)),
        'media': value['media'] == null ? undefined : ((value['media'] as Array<any>).map(DataportKulturfinderApiModelDataReadMediaToJSON)),
        'dataRights': value['dataRights'],
        'name': value['name'],
        'nameAddition': value['nameAddition'],
        'description': value['description'],
        'region': DataportKulturfinderApiModelDataReadRegionToJSON(value['region']),
        'address': value['address'],
        'zipCode': value['zipCode'],
        'city': value['city'],
        'longitude': value['longitude'],
        'latitude': value['latitude'],
        'communications': value['communications'] == null ? undefined : ((value['communications'] as Array<any>).map(DataportKulturfinderApiModelDataReadCommunicationToJSON)),
        'openingHours': value['openingHours'] == null ? undefined : ((value['openingHours'] as Array<any>).map(DataportKulturfinderApiModelDataReadOpeningHoursToJSON)),
        'closedDays': value['closedDays'] == null ? undefined : ((value['closedDays'] as Array<any>).map(DataportKulturfinderApiModelDataReadClosedDayToJSON)),
        'specialOpeningHours': value['specialOpeningHours'],
        'specialClosedDays': value['specialClosedDays'],
        'visible': value['visible'],
        'name_c_o': value['nameCO'],
        'hasLivingImages': value['hasLivingImages'],
    };
}

