/* tslint:disable */
/* eslint-disable */
/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataportKulturfinderApiModelDataLivingImageOffset } from './DataportKulturfinderApiModelDataLivingImageOffset';
import {
    DataportKulturfinderApiModelDataLivingImageOffsetFromJSON,
    DataportKulturfinderApiModelDataLivingImageOffsetFromJSONTyped,
    DataportKulturfinderApiModelDataLivingImageOffsetToJSON,
    DataportKulturfinderApiModelDataLivingImageOffsetToJSONTyped,
} from './DataportKulturfinderApiModelDataLivingImageOffset';

/**
 * 
 * @export
 * @interface DataportKulturfinderApiModelDataReadLivingImage
 */
export interface DataportKulturfinderApiModelDataReadLivingImage {
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadLivingImage
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadLivingImage
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadLivingImage
     */
    fsetUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadLivingImage
     */
    fset3Url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadLivingImage
     */
    isetUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataReadLivingImage
     */
    videoUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DataportKulturfinderApiModelDataReadLivingImage
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof DataportKulturfinderApiModelDataReadLivingImage
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof DataportKulturfinderApiModelDataReadLivingImage
     */
    scale?: number;
    /**
     * 
     * @type {DataportKulturfinderApiModelDataLivingImageOffset}
     * @memberof DataportKulturfinderApiModelDataReadLivingImage
     */
    offset?: DataportKulturfinderApiModelDataLivingImageOffset;
}

/**
 * Check if a given object implements the DataportKulturfinderApiModelDataReadLivingImage interface.
 */
export function instanceOfDataportKulturfinderApiModelDataReadLivingImage(value: object): value is DataportKulturfinderApiModelDataReadLivingImage {
    return true;
}

export function DataportKulturfinderApiModelDataReadLivingImageFromJSON(json: any): DataportKulturfinderApiModelDataReadLivingImage {
    return DataportKulturfinderApiModelDataReadLivingImageFromJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataReadLivingImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataportKulturfinderApiModelDataReadLivingImage {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'fsetUrl': json['fsetUrl'] == null ? undefined : json['fsetUrl'],
        'fset3Url': json['fset3Url'] == null ? undefined : json['fset3Url'],
        'isetUrl': json['isetUrl'] == null ? undefined : json['isetUrl'],
        'videoUrl': json['videoUrl'] == null ? undefined : json['videoUrl'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
        'scale': json['scale'] == null ? undefined : json['scale'],
        'offset': json['offset'] == null ? undefined : DataportKulturfinderApiModelDataLivingImageOffsetFromJSON(json['offset']),
    };
}

export function DataportKulturfinderApiModelDataReadLivingImageToJSON(json: any): DataportKulturfinderApiModelDataReadLivingImage {
    return DataportKulturfinderApiModelDataReadLivingImageToJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataReadLivingImageToJSONTyped(value?: DataportKulturfinderApiModelDataReadLivingImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'imageUrl': value['imageUrl'],
        'fsetUrl': value['fsetUrl'],
        'fset3Url': value['fset3Url'],
        'isetUrl': value['isetUrl'],
        'videoUrl': value['videoUrl'],
        'width': value['width'],
        'height': value['height'],
        'scale': value['scale'],
        'offset': DataportKulturfinderApiModelDataLivingImageOffsetToJSON(value['offset']),
    };
}

