/* tslint:disable */
/* eslint-disable */
/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataportKulturfinderApiModelDataWriteClosedDayMultiLingual } from './DataportKulturfinderApiModelDataWriteClosedDayMultiLingual';
import {
    DataportKulturfinderApiModelDataWriteClosedDayMultiLingualFromJSON,
    DataportKulturfinderApiModelDataWriteClosedDayMultiLingualFromJSONTyped,
    DataportKulturfinderApiModelDataWriteClosedDayMultiLingualToJSON,
    DataportKulturfinderApiModelDataWriteClosedDayMultiLingualToJSONTyped,
} from './DataportKulturfinderApiModelDataWriteClosedDayMultiLingual';
import type { DataportKulturfinderApiModelDataReadCommunication } from './DataportKulturfinderApiModelDataReadCommunication';
import {
    DataportKulturfinderApiModelDataReadCommunicationFromJSON,
    DataportKulturfinderApiModelDataReadCommunicationFromJSONTyped,
    DataportKulturfinderApiModelDataReadCommunicationToJSON,
    DataportKulturfinderApiModelDataReadCommunicationToJSONTyped,
} from './DataportKulturfinderApiModelDataReadCommunication';
import type { DataportKulturfinderApiModelDataWriteCategoryMultiLingual } from './DataportKulturfinderApiModelDataWriteCategoryMultiLingual';
import {
    DataportKulturfinderApiModelDataWriteCategoryMultiLingualFromJSON,
    DataportKulturfinderApiModelDataWriteCategoryMultiLingualFromJSONTyped,
    DataportKulturfinderApiModelDataWriteCategoryMultiLingualToJSON,
    DataportKulturfinderApiModelDataWriteCategoryMultiLingualToJSONTyped,
} from './DataportKulturfinderApiModelDataWriteCategoryMultiLingual';
import type { DataportKulturfinderApiModelDataWriteOpeningHoursMultiLingual } from './DataportKulturfinderApiModelDataWriteOpeningHoursMultiLingual';
import {
    DataportKulturfinderApiModelDataWriteOpeningHoursMultiLingualFromJSON,
    DataportKulturfinderApiModelDataWriteOpeningHoursMultiLingualFromJSONTyped,
    DataportKulturfinderApiModelDataWriteOpeningHoursMultiLingualToJSON,
    DataportKulturfinderApiModelDataWriteOpeningHoursMultiLingualToJSONTyped,
} from './DataportKulturfinderApiModelDataWriteOpeningHoursMultiLingual';
import type { DataportKulturfinderApiModelDataWriteTranslation } from './DataportKulturfinderApiModelDataWriteTranslation';
import {
    DataportKulturfinderApiModelDataWriteTranslationFromJSON,
    DataportKulturfinderApiModelDataWriteTranslationFromJSONTyped,
    DataportKulturfinderApiModelDataWriteTranslationToJSON,
    DataportKulturfinderApiModelDataWriteTranslationToJSONTyped,
} from './DataportKulturfinderApiModelDataWriteTranslation';
import type { DataportKulturfinderApiModelDataWriteTagMultiLingual } from './DataportKulturfinderApiModelDataWriteTagMultiLingual';
import {
    DataportKulturfinderApiModelDataWriteTagMultiLingualFromJSON,
    DataportKulturfinderApiModelDataWriteTagMultiLingualFromJSONTyped,
    DataportKulturfinderApiModelDataWriteTagMultiLingualToJSON,
    DataportKulturfinderApiModelDataWriteTagMultiLingualToJSONTyped,
} from './DataportKulturfinderApiModelDataWriteTagMultiLingual';
import type { DataportKulturfinderApiModelDataWriteRegionMultiLingual } from './DataportKulturfinderApiModelDataWriteRegionMultiLingual';
import {
    DataportKulturfinderApiModelDataWriteRegionMultiLingualFromJSON,
    DataportKulturfinderApiModelDataWriteRegionMultiLingualFromJSONTyped,
    DataportKulturfinderApiModelDataWriteRegionMultiLingualToJSON,
    DataportKulturfinderApiModelDataWriteRegionMultiLingualToJSONTyped,
} from './DataportKulturfinderApiModelDataWriteRegionMultiLingual';
import type { DataportKulturfinderApiModelDataWriteMediaMultiLingual } from './DataportKulturfinderApiModelDataWriteMediaMultiLingual';
import {
    DataportKulturfinderApiModelDataWriteMediaMultiLingualFromJSON,
    DataportKulturfinderApiModelDataWriteMediaMultiLingualFromJSONTyped,
    DataportKulturfinderApiModelDataWriteMediaMultiLingualToJSON,
    DataportKulturfinderApiModelDataWriteMediaMultiLingualToJSONTyped,
} from './DataportKulturfinderApiModelDataWriteMediaMultiLingual';

/**
 * 
 * @export
 * @interface DataportKulturfinderApiModelDataWriteInstituteMultiLingual
 */
export interface DataportKulturfinderApiModelDataWriteInstituteMultiLingual {
    /**
     * 
     * @type {number}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    id?: number;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataWriteCategoryMultiLingual>}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    categories?: Array<DataportKulturfinderApiModelDataWriteCategoryMultiLingual> | null;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataWriteTagMultiLingual>}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    tags?: Array<DataportKulturfinderApiModelDataWriteTagMultiLingual> | null;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataWriteMediaMultiLingual>}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    media?: Array<DataportKulturfinderApiModelDataWriteMediaMultiLingual> | null;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataReadCommunication>}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    communications?: Array<DataportKulturfinderApiModelDataReadCommunication> | null;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataWriteOpeningHoursMultiLingual>}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    openingHours?: Array<DataportKulturfinderApiModelDataWriteOpeningHoursMultiLingual> | null;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataWriteClosedDayMultiLingual>}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    closedDays?: Array<DataportKulturfinderApiModelDataWriteClosedDayMultiLingual> | null;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataWriteTranslation>}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    specialOpeningHours?: Array<DataportKulturfinderApiModelDataWriteTranslation> | null;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataWriteTranslation>}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    specialClosedDays?: Array<DataportKulturfinderApiModelDataWriteTranslation> | null;
    /**
     * 
     * @type {boolean}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    visible?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    dataRights?: string | null;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataWriteTranslation>}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    name?: Array<DataportKulturfinderApiModelDataWriteTranslation> | null;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataWriteTranslation>}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    nameAddition?: Array<DataportKulturfinderApiModelDataWriteTranslation> | null;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataWriteTranslation>}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    description?: Array<DataportKulturfinderApiModelDataWriteTranslation> | null;
    /**
     * 
     * @type {DataportKulturfinderApiModelDataWriteRegionMultiLingual}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    region?: DataportKulturfinderApiModelDataWriteRegionMultiLingual;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataWriteTranslation>}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    address?: Array<DataportKulturfinderApiModelDataWriteTranslation> | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    nameCO?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    zipCode?: string | null;
    /**
     * 
     * @type {Array<DataportKulturfinderApiModelDataWriteTranslation>}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    city?: Array<DataportKulturfinderApiModelDataWriteTranslation> | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    longitude?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataWriteInstituteMultiLingual
     */
    latitude?: string | null;
}

/**
 * Check if a given object implements the DataportKulturfinderApiModelDataWriteInstituteMultiLingual interface.
 */
export function instanceOfDataportKulturfinderApiModelDataWriteInstituteMultiLingual(value: object): value is DataportKulturfinderApiModelDataWriteInstituteMultiLingual {
    return true;
}

export function DataportKulturfinderApiModelDataWriteInstituteMultiLingualFromJSON(json: any): DataportKulturfinderApiModelDataWriteInstituteMultiLingual {
    return DataportKulturfinderApiModelDataWriteInstituteMultiLingualFromJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataWriteInstituteMultiLingualFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataportKulturfinderApiModelDataWriteInstituteMultiLingual {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'categories': json['categories'] == null ? undefined : ((json['categories'] as Array<any>).map(DataportKulturfinderApiModelDataWriteCategoryMultiLingualFromJSON)),
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTagMultiLingualFromJSON)),
        'media': json['media'] == null ? undefined : ((json['media'] as Array<any>).map(DataportKulturfinderApiModelDataWriteMediaMultiLingualFromJSON)),
        'communications': json['communications'] == null ? undefined : ((json['communications'] as Array<any>).map(DataportKulturfinderApiModelDataReadCommunicationFromJSON)),
        'openingHours': json['openingHours'] == null ? undefined : ((json['openingHours'] as Array<any>).map(DataportKulturfinderApiModelDataWriteOpeningHoursMultiLingualFromJSON)),
        'closedDays': json['closedDays'] == null ? undefined : ((json['closedDays'] as Array<any>).map(DataportKulturfinderApiModelDataWriteClosedDayMultiLingualFromJSON)),
        'specialOpeningHours': json['specialOpeningHours'] == null ? undefined : ((json['specialOpeningHours'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTranslationFromJSON)),
        'specialClosedDays': json['specialClosedDays'] == null ? undefined : ((json['specialClosedDays'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTranslationFromJSON)),
        'visible': json['visible'] == null ? undefined : json['visible'],
        'dataRights': json['dataRights'] == null ? undefined : json['dataRights'],
        'name': json['name'] == null ? undefined : ((json['name'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTranslationFromJSON)),
        'nameAddition': json['nameAddition'] == null ? undefined : ((json['nameAddition'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTranslationFromJSON)),
        'description': json['description'] == null ? undefined : ((json['description'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTranslationFromJSON)),
        'region': json['region'] == null ? undefined : DataportKulturfinderApiModelDataWriteRegionMultiLingualFromJSON(json['region']),
        'address': json['address'] == null ? undefined : ((json['address'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTranslationFromJSON)),
        'nameCO': json['name_c_o'] == null ? undefined : json['name_c_o'],
        'zipCode': json['zipCode'] == null ? undefined : json['zipCode'],
        'city': json['city'] == null ? undefined : ((json['city'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTranslationFromJSON)),
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
    };
}

export function DataportKulturfinderApiModelDataWriteInstituteMultiLingualToJSON(json: any): DataportKulturfinderApiModelDataWriteInstituteMultiLingual {
    return DataportKulturfinderApiModelDataWriteInstituteMultiLingualToJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataWriteInstituteMultiLingualToJSONTyped(value?: DataportKulturfinderApiModelDataWriteInstituteMultiLingual | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'categories': value['categories'] == null ? undefined : ((value['categories'] as Array<any>).map(DataportKulturfinderApiModelDataWriteCategoryMultiLingualToJSON)),
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTagMultiLingualToJSON)),
        'media': value['media'] == null ? undefined : ((value['media'] as Array<any>).map(DataportKulturfinderApiModelDataWriteMediaMultiLingualToJSON)),
        'communications': value['communications'] == null ? undefined : ((value['communications'] as Array<any>).map(DataportKulturfinderApiModelDataReadCommunicationToJSON)),
        'openingHours': value['openingHours'] == null ? undefined : ((value['openingHours'] as Array<any>).map(DataportKulturfinderApiModelDataWriteOpeningHoursMultiLingualToJSON)),
        'closedDays': value['closedDays'] == null ? undefined : ((value['closedDays'] as Array<any>).map(DataportKulturfinderApiModelDataWriteClosedDayMultiLingualToJSON)),
        'specialOpeningHours': value['specialOpeningHours'] == null ? undefined : ((value['specialOpeningHours'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTranslationToJSON)),
        'specialClosedDays': value['specialClosedDays'] == null ? undefined : ((value['specialClosedDays'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTranslationToJSON)),
        'visible': value['visible'],
        'dataRights': value['dataRights'],
        'name': value['name'] == null ? undefined : ((value['name'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTranslationToJSON)),
        'nameAddition': value['nameAddition'] == null ? undefined : ((value['nameAddition'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTranslationToJSON)),
        'description': value['description'] == null ? undefined : ((value['description'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTranslationToJSON)),
        'region': DataportKulturfinderApiModelDataWriteRegionMultiLingualToJSON(value['region']),
        'address': value['address'] == null ? undefined : ((value['address'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTranslationToJSON)),
        'name_c_o': value['nameCO'],
        'zipCode': value['zipCode'],
        'city': value['city'] == null ? undefined : ((value['city'] as Array<any>).map(DataportKulturfinderApiModelDataWriteTranslationToJSON)),
        'longitude': value['longitude'],
        'latitude': value['latitude'],
    };
}

