/* tslint:disable */
/* eslint-disable */
/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataportKulturfinderApiModelDataJwtTokenResponse
 */
export interface DataportKulturfinderApiModelDataJwtTokenResponse {
    /**
     * 
     * @type {string}
     * @memberof DataportKulturfinderApiModelDataJwtTokenResponse
     */
    token?: string | null;
}

/**
 * Check if a given object implements the DataportKulturfinderApiModelDataJwtTokenResponse interface.
 */
export function instanceOfDataportKulturfinderApiModelDataJwtTokenResponse(value: object): value is DataportKulturfinderApiModelDataJwtTokenResponse {
    return true;
}

export function DataportKulturfinderApiModelDataJwtTokenResponseFromJSON(json: any): DataportKulturfinderApiModelDataJwtTokenResponse {
    return DataportKulturfinderApiModelDataJwtTokenResponseFromJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataJwtTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataportKulturfinderApiModelDataJwtTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function DataportKulturfinderApiModelDataJwtTokenResponseToJSON(json: any): DataportKulturfinderApiModelDataJwtTokenResponse {
    return DataportKulturfinderApiModelDataJwtTokenResponseToJSONTyped(json, false);
}

export function DataportKulturfinderApiModelDataJwtTokenResponseToJSONTyped(value?: DataportKulturfinderApiModelDataJwtTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

