/* tslint:disable */
/* eslint-disable */
/**
 * Kulturfinder Bremen API
 * An ASP.NET Core Web API for managing the Data of Institutions
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DataportKulturfinderApiModelDataWriteTagMultiLingual,
  MicrosoftAspNetCoreMvcProblemDetails,
} from '../models/index';
import {
    DataportKulturfinderApiModelDataWriteTagMultiLingualFromJSON,
    DataportKulturfinderApiModelDataWriteTagMultiLingualToJSON,
    MicrosoftAspNetCoreMvcProblemDetailsFromJSON,
    MicrosoftAspNetCoreMvcProblemDetailsToJSON,
} from '../models/index';

export interface TagDeleteTagIdDeleteRequest {
    id: number;
}

export interface TagUpdateTagPutRequest {
    dataportKulturfinderApiModelDataWriteTagMultiLingual?: DataportKulturfinderApiModelDataWriteTagMultiLingual;
}

/**
 * 
 */
export class TagApi extends runtime.BaseAPI {

    /**
     * Deletes a Tag by the given id
     */
    async tagDeleteTagIdDeleteRaw(requestParameters: TagDeleteTagIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling tagDeleteTagIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/Tag/DeleteTag/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a Tag by the given id
     */
    async tagDeleteTagIdDelete(requestParameters: TagDeleteTagIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.tagDeleteTagIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Gets a List of all Tags
     */
    async tagGetTagsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DataportKulturfinderApiModelDataWriteTagMultiLingual>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/Tag/GetTags`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DataportKulturfinderApiModelDataWriteTagMultiLingualFromJSON));
    }

    /**
     * Gets a List of all Tags
     */
    async tagGetTagsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DataportKulturfinderApiModelDataWriteTagMultiLingual> | null | undefined > {
        const response = await this.tagGetTagsGetRaw(initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * Updates a Tag and overwrites all Informations by the given values
     */
    async tagUpdateTagPutRaw(requestParameters: TagUpdateTagPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/Tag/UpdateTag`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: DataportKulturfinderApiModelDataWriteTagMultiLingualToJSON(requestParameters['dataportKulturfinderApiModelDataWriteTagMultiLingual']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates a Tag and overwrites all Informations by the given values
     */
    async tagUpdateTagPut(requestParameters: TagUpdateTagPutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.tagUpdateTagPutRaw(requestParameters, initOverrides);
    }

}
